Feat/e2e tests
WildCodeSchool/2209-wns-adleman-eco-co-challenges pull request #83
Opened 2023-04-26 09:12 UTC by Aslb17

2023-04-26 09:17 UTC, antoinedumez requested changes

2023-04-26 09:17 UTC, antoinedumez commented on e2e-tests/playwright.config.ts
dead code :)

2023-04-26 09:17 UTC, antoinedumez commented on server/.env
why this modifications ?

2023-04-27 07:23 UTC, MarcHazime approved these changes

2023-04-27 08:02 UTC, merged